### ISSUE TITLE
Issue after npm install

### ISSUE THREAD

**Issue by marticrespi** [NishanthKabra/Ionic2_GoogleCalendar#1]
Hi,

I have clone your repo and when I try to run the server, its show me two compilation errors. Can you help me? 

`TypeScript error: xxxxxx/app/pages/GoogleCalendar/googleCalendar.ts(2,23): 
Error TS2305: Module '"xxxxxx/node_modules/ionic-native/dist/index"' has no exported member 'InAppBrowserEvent'.`

`TypeScript error: xxxxxx/app/pages/GoogleCalendar/googleCalendar.ts(2,42): 
Error TS2305: Module '"xxxxxx/node_modules/ionic-native/dist/index"' has no exported member 'InAppBrowserRef'.`

Looks awesome your work!

**Comment by NishanthKabra** [comment]
Hi @marticrespi , i think you are missing the following code in your code of googleCalendar.ts 
`interface BrowserEvent extends InAppBrowserEvent{
}
interface BrowserRef extends InAppBrowserRef{
  addEventListener(type: string, callback: (event: InAppBrowserEvent) => void): any;
}`

Let me know if it resolves the issue.
An also, deploy this app to a device and only then test the features.

**Comment by marticrespi** [comment]
Hi @NishanthKabra , I only have downloaded your code and try to serve! I already have this code, in the top of the typescript class. It fails the import, not extending custom interfaces.

https://i.imgbox.com/dRB2hCaX.png

Thanks!

**Comment by NishanthKabra** [comment]
@marticrespi i think there are some issues related to typescript definitions, i want you to check your diectory "node_modules\ionic-native\dist\plugins" and make sure you have the following files "inappbrowser.d.ts", "inappbrowser.js", inappbrowser.js.map. Then you probably would not get the red squiggly for InAppBrowerEvent, InAppBrowserRef and solution should build. I have attached the contents of the file "inappbrowser.d.ts", please look at it and see if you are missing anything.

[InAppBrowser.txt](https://github.com/NishanthKabra/Ionic2_GoogleCalendar/files/618619/InAppBrowser.txt)


Do respond again if you fail to build. Lets fix it together. Thanks.

**Comment by SOMONSOUM** [comment]
@NishanthKabra  I Couldn't find folder dist in ionic-native. Could you please help me?
Thanks in advance

**Comment by SOMONSOUM** [comment]
![screenshot 360](https://user-images.githubusercontent.com/28615575/30374528-765792fa-98af-11e7-90bd-ee24daa1cb67.png)
![screenshot 359](https://user-images.githubusercontent.com/28615575/30374527-764fbf80-98af-11e7-8bf9-fce7486d71f0.png)

**Comment by ghost** [comment]
node_modules/@ionic-native/in-app-browser/index"' has no exported member 'InAppBrowserRef'.
import { InAppBrowser,InAppBrowserEvent, InAppBrowserRef } from '@ionic-native/in-app-browser';

Property 'open' does not exist on type 'typeof InAppBrowser'.
var browserRef = InAppBrowser.open('https://accounts.google.com/o/oauth2/auth?client_id=' + this.CLIENT_ID + '&redirect_uri=' + this.REDIRECTURL + '&scope=https://www.googleapis.com/auth/calendar&approval_prompt=force&response_type=token', '_blank', 'location=no');

How do i solve this issue can any one help me

**Comment by jainnishtha22** [comment]
Hi, 
i took your code from repo but getting same error => 
Ionic2_GoogleCalendar-master/node_modules/ionic-native/dist/index"' has no exported member 'InAppBrowserEvent'

i checked my directory and im having following files
 inappbrowser.d.ts", "inappbrowser.js", inappbrowser.js.map. but still not able to remove error.



can you please help
